# Generated by Django 3.1.4 on 2020-12-20 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('estagio_da_obra', models.IntegerField(choices=[(1, 'Em Definição'), (2, 'Em Construção'), (3, 'Entregue')])),
                ('capa', models.ImageField(upload_to='casas/capas/')),
                ('icone', models.ImageField(upload_to='casas/icones/')),
                ('data_de_entrega', models.DateField()),
                ('metragem_do_terreno', models.DecimalField(decimal_places=2, max_digits=20)),
                ('metragem_da_casa', models.DecimalField(decimal_places=2, max_digits=20)),
                ('condominio', models.CharField(max_length=200)),
                ('endereco', models.CharField(max_length=400)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=20)),
                ('comentarios', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empreendimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('endereco', models.CharField(max_length=400)),
                ('capa', models.ImageField(upload_to='empreendimentos/capas/')),
                ('icone', models.ImageField(upload_to='empreendimentos/icones/')),
                ('entrega', models.DateField()),
                ('comentarios', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=100)),
                ('metragem', models.IntegerField()),
                ('vaga', models.CharField(max_length=100)),
                ('tipo_de_vaga', models.IntegerField(choices=[(1, 'Coberta(s)'), (2, 'Descoberta(s)'), (3, 'Coberta(s) e descoberta(s)')])),
                ('sinal_na_assinatura_do_contrato', models.DecimalField(decimal_places=2, max_digits=20)),
                ('restante_da_entrada', models.DecimalField(decimal_places=2, max_digits=20)),
                ('boxe', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=20)),
                ('valor_promocional', models.DecimalField(decimal_places=2, max_digits=20)),
                ('situacao', models.BooleanField(default=False)),
                ('empreendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.empreendimento')),
            ],
        ),
        migrations.CreateModel(
            name='MidiaEmpreendimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[(1, 'Link'), (2, 'Foto'), (3, 'Video'), (4, 'Arquivo')])),
                ('link', models.URLField(blank=True, max_length=1000, null=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='empreendimentos/arquivos/')),
                ('empreendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.empreendimento')),
            ],
        ),
        migrations.CreateModel(
            name='MidiaCasa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[(1, 'Link'), (2, 'Foto'), (3, 'Video'), (4, 'Arquivo')])),
                ('link', models.URLField(blank=True, max_length=1000, null=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='casas/arquivos/')),
                ('casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.casa')),
            ],
        ),
    ]
