# Generated by Django 3.1.4 on 2020-12-20 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unidade',
            old_name='situacao',
            new_name='vendida',
        ),
    ]
