# Generated by Django 3.1.4 on 2020-12-20 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20201220_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casa',
            name='capa',
        ),
        migrations.RemoveField(
            model_name='empreendimento',
            name='capa',
        ),
    ]
