# Generated by Django 3.1.4 on 2020-12-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20201220_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='midiaempreendimento',
            name='nome',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
    ]
