# Generated by Django 3.1.4 on 2020-12-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_midiaempreendimento_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidade',
            name='valor_promocional',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
