# Generated by Django 3.1.4 on 2020-12-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20201220_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidade',
            name='tipo_de_vaga',
            field=models.IntegerField(blank=True, choices=[(1, 'Coberta(s)'), (2, 'Descoberta(s)'), (3, 'Coberta(s) e descoberta(s)')], null=True),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='vaga',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
