# Generated by Django 3.1.4 on 2020-12-20 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_auto_20201220_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='midiacasa',
            name='nome',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
