# Generated by Django 3.1.4 on 2020-12-20 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_midiacasa_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casa',
            old_name='data_de_entrega',
            new_name='entrega',
        ),
    ]
